### ISSUE TITLE
Prompt-blocking behavior from the perviewer

### ISSUE THREAD

**Issue by N247S** [SimonSiefke/vscode-html-preview#24]
Goodday,

I found another bug (which might be one for the underlaying js project?)
I setup a small testcase so you can see what the problem is.

**Test case:**

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div>testing</div> <!-- try to type this line in preview mode on browser -->
</body>
</html>
```

**Steps to reproduce:**

1. create a file with an empty html template (like above, excluding the `div` element).
2. open the preview (if you open it in browser you'll get the notifications, in VSCode it simply freezes without notifications, as javascript is verry restricted in VSCode).
3. start typing the element without autocompletion
4. watch the magic happen.

**Error message**

```
errorhighlight error, node 11 doesn't exist
```

In this case it gave the element the number `11` but it can be any element/number. I get that the html structure is invalid, so that it is not highlighting correctly is fine (since I am still typing). The problem is that it is prompting, and therefore blocking all javascript executions. Since the event queue contineus when you type further, the popup seems to be 'unhidable' as the same error is generated for every single event it runs behind. This not only blocks javascript events, it also blocks the updating of the html-preview itself (hence the blocking in VSCode)

My solution is to simply refresh the browser, after which you only need to click the popup away once. But that is an extra step this plugin should prevent IMO (pressing f5 after every change).
If I have the preview in VSCode, there is no way to refresh the embedded browser, So than I have to close the preview, and reopen it (which is also not ideal).

**Proposed solution:**

As you mentioned in another issue post, there were problems with the `tbody` element, I would propose a  2step process for the highlighting and updating?

As you cannot expect the html structure to be perfect (half-typed elements, unclosed elements etc.), I would propose a 'validation-step' before 'reacting' on the event send from VSCode? So when it senses its html structure is invalid, simply abort advanced highlighting stuff and put something in the logs instead of trying to prompt everytime?

Once it has been invalid, and it senses a valid HTML structure again, simply rebuild the structure (as it is doing when you first open the preview) and everything should work fine. This step can also be used to 'fix' the `tbody` issue I guese?

As a side-note I would advice to add a logging-level setting for the plugin, as one might be more interested in errors from his own javascript rather than a spam of this plugin?

version details:
    Html Preview 1.21.5

If you need more information, feel free to ask!

**Comment by SimonSiefke** [comment]
Yeah that's annoying. I put that in there to show actual errors in the implementation of the parser/diffing. 

I've pushed an update to only log the error to the console.

But I think the optimal solution would be a better parser that can detect whether the code is valid or not and only update if it is valid as you said. I'm still not entirely sure about the tbody issue since a table without a tbody is valid html, it's just that the browser automatically inserts a tbody. 

```html
<table>
	<tr><td>1</td></tr>
	<tr><td>2</td></tr>
</table>
```

When you add a another tr, the diff algorithm will determine that you added a tr inside the table. However the tr must be added into the tbody that the browser has added. If the parser would also just add a tbody node, the diff would work correctly. I'll try to implement that.

**Comment by SimonSiefke** [comment]
Should be much better in v2.0.4. If something still isn't working, feel free to open another issue.
