### ISSUE TITLE
No live update when base tag used

### ISSUE THREAD

**Issue by NostraDavid** [SimonSiefke/vscode-html-preview#26]
Using the HTML below somehow breaks the live update. If you remove the `base` tag and re-open the preview window, it will work again.

``` HTML
<!DOCTYPE html>
<html>
  <head>
    <base href=http://www.example.com/ target=_self />
  </head>
  <body>
    asdasdasdasdasdasd
  </body>
</html>
```

However, that is not the only thing, as [this HTML](https://gist.github.com/NostraDavid/264b995714c340d00b97026dd0d8224c) doesn't get fixed when I remove the `base` tag, so there has to be other tags breaking the extension.

**Comment by SimonSiefke** [comment]
I've fixed the base tag issue, so this code now works:

```html
<!DOCTYPE html>
<html>
  <head>
    <base href="http://www.example.com/" target="_self" />
  </head>
  <body>
    asdasdasdasdasdasd

  </body>
</html>
```

I still need to fix the parser because it sometimes fails when it encounters an attribute without quotes like `<base href=http://www.example.com/  />`

**Comment by SimonSiefke** [comment]
I've fixed the parser so that it now works with all valid HTML. 

I've also checked out your link and noticed that it contains some invalid HTML:

```html
<!-- 1. Nested p tag is not allowed -->
<p> Costello: Look, you gotta first baseman?
        <p> Abbott: Certainly.</p>

<!-- 2. Closing </p> tag is not allowed inside the span -->
  <p> <b>Shopkeeper</b>: Sorry, <span title="This is, of course, a lie.">we're</p> closing for lunch</span>.
```

After fixing the HTML the page should reload and you should be able to edit the file and see the updates as you type. Let me know if that works.
