### ISSUE TITLE
Live preview stop working

### ISSUE THREAD

**Issue by jovinhz** [SimonSiefke/vscode-html-preview#27]
Live preview sometimes stops working in certain occasions. The webpage just keep freezing and cannot reload the page.

Some occasions that make this happen are :
- try to comment and remove comment continuously on any css code for 8 times or more.
- link and unlink  <link> css file.
- when working on css file the live preview often got bugged and stopped working

My browser : Mozilla Firefox v75.0

**Comment by SimonSiefke** [comment]
> Live preview sometimes stops working in certain occasions
Should be much better in v2.0.4

If something still isn't working, feel free to open another issue
